site_name: click 代码文档
theme:
  name: material
docs_dir: .
nav:
  - 架构总览: index.md
  - 模块:
      - tests: modules/tests.md
      - src/click: modules/src_click.md
      - examples/imagepipe: modules/examples_imagepipe.md
      - examples/aliases: modules/examples_aliases.md
      - tests/typing: modules/tests_typing.md
      - examples/termui: modules/examples_termui.md
      - examples/repo: modules/examples_repo.md
      - examples/complex: modules/examples_complex.md
      - examples/naval: modules/examples_naval.md
      - examples/completion: modules/examples_completion.md
      - examples/validation: modules/examples_validation.md
      - examples/colors: modules/examples_colors.md
